<a href="https://colab.research.google.com/github/Farhan0140/CSE-Lab-Courses/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Scalar & Array Operations

In [ ]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

Run the given code with scalar = 3.7 and a new array of at least 6 elements.

In [ ]:
# Sample scalar and array inputs
scalar = 3.7
arr = np.array([62,8,1.2,45.7786,6,9])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

# Exponential and logarithm
exp_values = np.exp(arr)
log_values = np.log(arr)  # Natural logarithm

# Absolute value and square root
abs_values = np.abs(arr)
sqrt_values = np.sqrt(arr)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(arr, 2)

# Rounding functions
round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("abs:", abs_values)
print("sqrt:", sqrt_values)
print("rem:", rem_values)
print("round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)

sin: [-0.7391807   0.98935825  0.93203909  0.97468097 -0.2794155   0.41211849]
cos: [ 0.67350716 -0.14550003  0.36235775 -0.22360009  0.96017029 -0.91113026]
tan: [-1.09750978 -6.79971146  2.57215162 -4.35903661 -0.29100619 -0.45231566]
asin: [1.57079633 0.12939302 0.01935605 0.83064204 0.09692589 0.14567599]
acos: [0.         1.44140331 1.55144028 0.74015429 1.47387044 1.42512034]
atan: [1.55466869 1.44644133 0.87605805 1.54895553 1.40564765 1.46013911]
exp: [8.43835667e+26 2.98095799e+03 3.32011692e+00 7.61015267e+19
 4.03428793e+02 8.10308393e+03]
log: [4.12713439 2.07944154 0.18232156 3.82381673 1.79175947 2.19722458]
abs: [62.      8.      1.2    45.7786  6.      9.    ]
sqrt: [7.87400787 2.82842712 1.09544512 6.76598847 2.44948974 3.        ]
rem: [0.     0.     1.2    1.7786 0.     1.    ]
round: [62.  8.  1. 46.  6.  9.]
floor: [62.  8.  1. 45.  6.  9.]
ceil: [62.  8.  2. 46.  6.  9.]


3×2 Matrix Calculations

In [ ]:
# Creating a matrix (3x2)
matrix = np.array([[1.000, 242],
                   [3.47875, -4.67],
                   [500, -6]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)

# Normalize for inverse trig functions
normalized = np.clip(matrix / np.max(matrix), -1, 1)

asin_values = np.arcsin(normalized)
acos_values = np.arccos(normalized)
atan_values = np.arctan(matrix)

# Exponential
exp_values = np.exp(matrix)

# Logarithm (only for positive values)
log_values = np.full(matrix.shape, np.nan, dtype=float)

# Absolute value
abs_values = np.abs(matrix)

# Square root (only for non-negative values)
sqrt_values = np.full(matrix.shape, np.nan, dtype=float)

# Remainder
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasin:\n", asin_values)
print("\nacos:\n", acos_values)
print("\natan:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural, safe):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt (safe):\n", sqrt_values)
print("\nremainder (mod 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[  1.      242.     ]
 [  3.47875  -4.67   ]
 [500.       -6.     ]]

sin:
 [[ 0.84147098 -0.09721191]
 [-0.33080582  0.99910172]
 [-0.46777181  0.2794155 ]]

cos:
 [[ 0.54030231 -0.99526371]
 [-0.94369884 -0.04237629]
 [-0.88384927  0.96017029]]

tan:
 [[  1.55740772   0.09767452]
 [  0.35054173 -23.57690554]
 [  0.52924386   0.29100619]]

asin:
 [[ 0.002       0.50522004]
 [ 0.00695756 -0.00934014]
 [ 1.57079633 -0.01200029]]

acos:
 [[1.56879633 1.06557629]
 [1.56383877 1.58013646]
 [0.         1.58279661]]

atan:
 [[ 0.78539816  1.56666412]
 [ 1.29088384 -1.35984924]
 [ 1.56879633 -1.40564765]]

exp:
 [[2.71828183e+000 1.25679551e+105]
 [3.24191728e+001 9.37226953e-003]
 [1.40359222e+217 2.47875218e-003]]

log (natural, safe):
 [[nan nan]
 [nan nan]
 [nan nan]]

abs:
 [[  1.      242.     ]
 [  3.47875   4.67   ]
 [500.        6.     ]]

sqrt (safe):
 [[nan nan]
 [nan nan]
 [nan nan]]

remainder (mod 2):
 [[1.      0.     ]
 [1.47875 1.33   ]
 [0.      0.     ]]

round:
 